<!DOCTYPE html>
<html>
<head>
    <title>Grow Fortuna - PDF Mail</title>
</head>
<body>
    <p>Dear {{$risk['riskmodel']->name ?? ''}},</p>
    <p>Thanks for choosing us!!</p>
    <p>Here at Grow Fortuna we understand your priorities and needs of clients and strive to provide our service at the utmost level.</p>
    <p>After analyzing your risk profile, our risk assessment team has given you a score of {{$risk['riskmodel']->totalpoints ?? ''}} out of 20. The product suitability according to your score is being attached with this mail. If your risk tolerance differs from what we have assessed, kindly let us know as soon as possible else the risk profile and risk suitability will be treated as true and deemed to be accepted by you.</p>
    <p>For more detail kindly find the ATTACHMENT with this mail.</p>
    <p>Important tips:</p>
    <ol>
        <li>Please use stop loss and target in advance during trading.</li>
        <li>Communicate your risk appetite with our executive.</li>
        <li>Neither Grow Fortuna nor its employees provide any surety or guarantee about profit in the market.</li>
        <li>We do not handle the DEMAT account of the client and also we do not execute the order on behalf of the client. If any person from Grow Fortuna asks for credentials of the Demat account then kindly write us on compliance@growfortuna.com.</li>
        <li>All the recommendations that will be provided are delivered by the Investment Advisor Mr. Manu Chhabra via the route of sms/Mobile Application/Phone Calls and other channels of communication. In case you have any query in regards to the delivered recommendations, kindly feel free to email us over services@growfortuna.com.</li>
        <li>For more detail about our Privacy Policy, Terms, and Condition, Disclaimer, and Disclosure kindly visit us at www.growfortuna.com.</li>
    </ol>
    <p>Thanks and Regards,<br>Grow Fortuna</p>
    <p>Important Info- The information contained in these documents is confidential, privileged and only for the information of the intended recipient. Presented by Mr.Dhruvin Bhanushali (Prop of Grow Fortuna, SEBI registration category- Proprietor, SEBI RIA registration number: INA000019017, validity of registration -March 2024  to Perpetual, Principal place of business- 1102 C-Wing Olive Building, Dindayal Upadhyay Marg,
    Neptune CHS Beside Croma, Mumbai, Mulund West, Maharashtra, 40080, Contact No - +91 9930906921, grievance@growfortuna.com, Principal Officer - Manu Chhabra, Contact No - +91 8792921955, compliance@growfortuna.com</p>
    <p>Disclaimer: The information is only for consumption by the client & such material should not be redistributed. This document is presented by Mr. Manu Chhabra Proprietor of Grow Fortuna, registered under SEBI (Investment Advisers) Regulation, 2013. The sole purpose of this document is to benefit and internal use of the recipient, no rights are availed to reuse or disclose the document. Without the prior written approval from Grow Fortuna, neither this document nor any content can be used irrespective of the purpose of use. On the way of preparation of this document, we have made a couple of assumptions and relied on information available in public sources and we don't owe the accuracy and completeness of the information. These assumptions and views are reasonably good to adopt but may subject to change in the future. Current market prices and general market sentiments are considered in the computation and Grow Fortuna doesn't represent or warranty these assumptions. This document doesn't claim to provide all the information required by the recipient. Information furnished on business, finance, legal, tax or other subjects should not be interpreted as advice neither in the present nor in future and recipients are suggested to consult respective advisors to make the right investment in securities. Needless to mention investment in equity and equity-related securities involves risk so investors are advised to invest only if they can afford to handle losses. Investors are also advised to do own examination of companies and avail advice from experts. Investors need to understand the price of securities may fluctuate anytime and result in loss. If any direct, indirect, special, incidental, consequential, punitive or exemplary damages, occur neither Grow Fortuna nor its employees are responsible in any way. This document doesn't form any kind of contract nor does it make any offer for sale, or invitation to subscribe for or purchase securities of the company. In no way, this document means or constitutes any kind of offer or transaction. Grow Fortuna or any of its stakeholders like affiliates, officers, directors, key managerial persons, and employees, including persons involved in the preparation or issuance of this material may sell or buy securities of the company/companies mentioned here. Grow Fortuna doesn't guarantee or warranty or represents express or implied, with respect to the fairness, correctness, accuracy, adequacy, reasonableness, viability for any particular purpose or completeness of the information and opinions. The securities quoted are for illustration only and are not recommendatory. Registration granted by SEBI, membership of BASL (in case of IAs) and certification from NISM in no way guarantee performance of the intermediary or provide any assurance of returns to investors. "Investment in securities market are subject to market risks. Read all the related documents carefully before investing.</p>
    <p>Services Limited to advisory only: The client is making payment for advisory services we do not take any kind of investments from clients nor we handle any Demat account. The services of Grow Fortuna are limited to providing trading signals to its clients. We do not ask for the DEMAT or Personal credentials from the clients. Grow Fortuna is an investment advisory firm that never trades on behalf of the subscriber. Also, any amount paid to us is only a subscription charge paid to avail our investment advisory services of market-related tips and recommendations. Grow Fortuna disclaims all liability in relation to the use of data or information used in this report which is sourced from third parties. Client acknowledges that the Advisor's investment recommendations involve some degree of risk. Client acknowledges that all investment activity in Client's Account shall be at Client's own risk, which can result in loss of Client's investment capital, annual income, and/or tax benefits. Client acknowledges that the Advisor will not reimburse Client for any losses. Client acknowledges that the Advisor’s past performance of recommended investments should not be construed as an indication of future results, which may prove to be better or worse than the past. Client acknowledges that the Advisor does not claim to be able to accurately predict the short-term future investment performance of any individual security or of a group of securities. Client acknowledges that the Advisor makes judgmental evaluations before providing investment advice for Client. In making judgmental evaluations, the Advisor agrees to use its best efforts to review sources of information that it has found to be valuable, accurate, and reliable. Client acknowledges that the Advisor cannot and does not survey all sources of publicly available information. Client acknowledges that the Advisor is not responsible for the accuracy or completeness of information furnished to the Advisor by Client or by any other party.</p>
    <p>
    According to SEBI PR No.: 03/2024 issued on 26th March 2024, we, operating under the brand name Grow Fortuna and on behalf of Mr. Dhruvin Bhanushali, do not provide advice on Digital gold, Non-fungible tokens (NFTs), Cryptocurrencies, or any other unregulated market products. If anyone claims otherwise in Mr. Dhruvin Bhanushali's name or under the Grow Fortuna brand, please do report to us the same over compliance@growfortuna.com.    
</p>
</body>
</html>
