<!DOCTYPE html>
<html>

<head>
<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Daily Reporting</title> 
    <style>
        body {
            font-family: 'Arial', sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f5f7fa;
            color: #333;
        }

        .container {
            max-width: 800px;
            margin: 20px auto;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            overflow: hidden;
        }

        .header {
            background-color: #002855;
            /* Matches logo color */
            color: #fff;
            padding: 20px;
            text-align: center;
        }

        .header img {
            max-width: 80px;
        }

        .header h1 {
            font-size: 22px;
            margin: 10px 0 5px;
            font-weight: bold;
        }

        .header p {
            font-size: 14px;
            margin: 0;
        }

        .summary {
            padding: 20px;
            border-bottom: 1px solid #ddd;
            background-color: #f9f9fc;
        }

        .summary h3 {
            font-size: 18px;
            margin-bottom: 10px;
        }

        .summary p {
            font-size: 14px;
            margin: 5px 0;
        }

        .task-details {
            padding: 20px;
        }

        .task-details table {
            width: 100%;
            border-collapse: collapse;
        }

        .task-details th {
            background-color: #f4f6f9;
            color: #333;
            text-align: left;
            padding: 10px;
            border-bottom: 2px solid #ddd;
        }

        .task-details td {
            padding: 10px;
            border-bottom: 1px solid #ddd;
        }

        .footer {
            text-align: center;
            padding: 15px;
            background-color: #002855;
            color: #fff;
            font-size: 14px;
        }

        .footer a {
            color: #a3c1f5;
            text-decoration: none;
        }
    </style>
</head>

<body>
    <div class="container">
        <!-- Header -->
        <div class="header">
            <img src="https://crm.volvrit.com/admin/images/volvrit.webp" style="width: 100px;" alt="Logo">
            <h1>Volvrit Daily Report</h1>
            <p>Automated Report | {{ date('Y-m-d') }}</p>
        </div>

        <!-- Summary Section -->
        <div class="summary">
            <h3>Summary</h3>
            <p><strong>Project Name :</strong> {{$phase_name}}</p>
            <p><strong>Task Name :</strong> {{$task_name}}</p>
            <p><strong>Task Status:</strong> {{$task_status}}</p>
            <p><strong>Project Overall Status : </strong> {{$project_status}}</p>
            <p><strong>Done By :</strong> {{Auth::user()->name}} {{Auth::user()->role}}</p>


        </div>

        <!-- Task Details Section -->
        <div class="task-details">
            <h3>Task Description</h3>
            <div class="summary">
                <p><strong> {!! $description !!}</strong></p>
                <p>File : <a href="https://crm.volvrit.com/{{$screenshot}}" target="__blank">View File</a></p>

            </div>
        </div>
        <div class="summary">
            <h3>Any Pending task</h3>
            <p><strong>Pending Task Name :</strong> {{$task_name ?? 'No Pending Task'}}</p>
            <p><strong>Pending Task Expected Completion Date :</strong> {{$pending_task_date ?? ''}}</p>

        </div>

        <!-- Footer -->
        <div class="footer">
            <p>Generated by Volvrit</p>
            <p>© 2024 Volvrit. All Rights Reserved.</p>
        </div>
    </div>
</body>

</html>